filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/logs/content-service/*.log
  fields:
    service: content-service
  json.keys_under_root: true
  json.add_error_key: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "content-service-%{+yyyy.MM.dd}" 