server:
  port: 8082

spring:
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 5MB        # 单个文件大小限制
      max-request-size: 10MB    # 总请求大小限制
      enabled: true
  application:
    name: media-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        heartbeat:
          enabled: true
          ttl: 30
        service-name: ${spring.application.name}
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
      circuitbreaker:
        enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/online_course?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 5000
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

# MinIO配置
minio:
  endpoint: http://localhost:9000
  accessKey: root
  secretKey: rootroot
  bucketName: media

# 自定义配置
media:
  image:
    max-size: 2097152          # 图片最大2MB (2 * 1024 * 1024)
    min-size: 1024             # 图片最小1KB
    allowed-types:             # 允许的图片类型
      - image/jpeg
      - image/png
      - image/gif



