server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  port: 8084
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        heartbeat:
          enabled: true
          ttl: 30
        service-name: ${spring.application.name}
  application:
    name: auth-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: flyway_schema_history
    validate-on-migrate: true
  data:
    # Redis配置
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 5000
      lettuce:
        pool:
          max-active: 8  # 最大连接数
          max-idle: 8    # 最大空闲连接
          min-idle: 0    # 最小空闲连接
          max-wait: -1ms # 连接等待时间

jwt:
  secret: ZDY1NmE3ZjI0ODdiNGZkZWJmZjk5MjExYjU4MzRlMzE2NzIwZWM0MjJmNmFlOWY5NzM2ZmRkMGM5NTYzYzE3YQ
  expiration: 86400000  # 24 hours