server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  port: 8084
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        heartbeat:
          enabled: true
          ttl: 30
        service-name: ${spring.application.name}
  application:
    name: auth-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: flyway_schema_history
    validate-on-migrate: true
  data:
    # Redis配置
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 5000
      lettuce:
        pool:
          max-active: 8  # 最大连接数
          max-idle: 8    # 最大空闲连接
          min-idle: 0    # 最小空闲连接
          max-wait: -1ms # 连接等待时间

jwt:
  secret: ZDY1NmE3ZjI0ODdiNGZkZWJmZjk5MjExYjU4MzRlMzE2NzIwZWM0MjJmNmFlOWY5NzM2ZmRkMGM5NTYzYzE3YQ
  expiration: 86400000  # 24 hours

# 内部客户端配置
app:
  client:
    web:
      secret: web-client-test-secret
    mobile:
      secret: mobile-client-test-secret

oidc:
  issuer: http://localhost:8084
  authorization-endpoint: /oauth2/authorize
  token-endpoint: /oauth2/token
  userinfo-endpoint: /oauth2/userinfo
  jwks-uri: /oauth2/jwks
  end-session-endpoint: /oauth2/logout
  scopes-supported:
    - openid
    - profile
    - email
    - phone
    - address
  response-types-supported:
    - code
  subject-types-supported:
    - public
  id-token-signing-alg-values-supported:
    - RS256
  claims-supported:
    - sub
    - iss
    - aud
    - exp
    - iat
    - name
    - family_name
    - given_name
    - middle_name
    - nickname
    - preferred_username
    - profile
    - picture
    - website
    - gender
    - birthdate
    - zoneinfo
    - locale
    - updated_at
    - email
    - email_verified
    - phone_number
    - phone_number_verified
    - organization_id