name: Java CI with Maven

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: 
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: online_course
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          
      redis:
        image: redis:6.2
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          
      minio:
        image: minio/minio
        ports:
          - 9000:9000
          - 9001:9001
        env:
          MINIO_ROOT_USER: root
          MINIO_ROOT_PASSWORD: rootroot
        options: >-
          --name=minio
          --health-cmd="curl -f http://localhost:9000/minio/health/live"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          
      consul:
        image: consul:1.15.4
        ports:
          - 8500:8500
        options: >-
          --health-cmd "consul info"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2-
    
    # 首先安装父项目
    - name: Install Parent Project
      run: mvn clean install -N
    
    # 然后构建并安装base模块
    - name: Build and Install Base Module
      run: mvn clean install -pl base
      
    # 等待MySQL启动
    - name: Wait for MySQL
      run: |
        while ! mysqladmin ping -h"127.0.0.1" --silent; do
          sleep 1
        done
    
    # 构建和测试content_service模块
    - name: Build and Test Content Service Module
      run: mvn clean verify -pl content_service -Dspring.profiles.active=test

    # 构建和测试media模块
    - name: Build and Test Media Module
      run: mvn clean verify -pl media -Dspring.profiles.active=test
